### ISSUE TITLE
ONNX转换报错：Failed to export model to ONNX: Exporting the operator 'aten::_convolution_mode' to ONNX opset version 17 is not supported

### ISSUE THREAD

**Issue by wjddd** [lars76/fastspeech2-clean#2]
使用[convert_to_onnx.py](https://github.com/lars76/fastspeech2-clean/blob/main/convert_to_onnx.py)将模型转为onnx时，出现以下报错：
```shell
RuntimeError: Failed to export model to ONNX: Exporting the operator 'aten::_convolution_mode' to ONNX opset version 17 is not supported.
```
我尝试将opset_version改为16、11、9都会出现同样的报错。

测试环境的相关依赖是：
```shell
onnx 1.16.0
onnxruntime 1.17.1
torch 1.13.1/2.0.1（有两套测试环境，torch1.x和2.x都测试过，均出现报错）
```
我参考了：https://github.com/pytorch/pytorch/issues/108975

将[lightspeech.py](https://github.com/lars76/fastspeech2-clean/blob/main/lightspeech.py)中的https://github.com/lars76/fastspeech2-clean/blob/3c538a5859bcd15d9058e09f0f577133d18dc83c/lightspeech.py#L26
改为
```python
padding = (kernel_size - 1) // 2
```
但还是会出现报错。

**Comment by lars76** [comment]
问题在使用 onnxruntime 1.18.0，onnx 1.16.1 和 torch 2.3.1 的环境下并不会发生。你提到的问题确实是由 "same" padding 导致的。在 HiFi-GAN vocoder中，我也使用了 "same" padding：https://github.com/lars76/bigvgan-mirror/blob/main/hifigan_mirror.py。你只需要升级这些库版本即可解决问题。

**Comment by wjddd** [comment]
> 问题在使用 onnxruntime 1.18.0，onnx 1.16.1 和 torch 2.3.1 的环境下并不会发生。你提到的问题确实是由 "same" padding 导致的。在 HiFi-GAN vocoder中，我也使用了 "same" padding：[https://github.com/lars76/bigvgan-mirror/blob/main/hifigan_mirror.py。你只需要升级这些库版本即可解决问题。](https://github.com/lars76/bigvgan-mirror/blob/main/hifigan_mirror.py%E3%80%82%E4%BD%A0%E5%8F%AA%E9%9C%80%E8%A6%81%E5%8D%87%E7%BA%A7%E8%BF%99%E4%BA%9B%E5%BA%93%E7%89%88%E6%9C%AC%E5%8D%B3%E5%8F%AF%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E3%80%82)

感谢您的回复~升级版本之后就可以正常运行onnx脚本了，测试了一下发现onnx和原版的合成速度是差不多的，这个是因为没有针对onnx进行优化导致的吗？（我以为onnx推理会更快一点）

**Comment by lars76** [comment]
可以试试使用以下代码进行量化：`quantized_model = onnxruntime.quantization.quantize_dynamic("input.onnx", "output.onnx", weight_type=onnxruntime.quantization.QuantType.QUInt8)`

**Comment by wjddd** [comment]
> 可以试试使用以下代码进行量化：`quantized_model = onnxruntime.quantization.quantize_dynamic("input.onnx", "output.onnx", weight_type=onnxruntime.quantization.QuantType.QUInt8)`

我测试了一下，发现int8会慢一倍左右，onnxruntime也有相关的issue：https://github.com/microsoft/onnxruntime/issues/6732

这个问题可能暂时无解，我先关闭这个issue，感谢您的答复~
